import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: { default: "Your Flex Aptia365", template: "Login" },

  description:
    "Registration and Log In Instruction Flyer · Forgot Your Password? Forgot Your Username? Received a Mailed Registration Code? Register as a New User?",

  keywords: [
    "aptia365",
    "aptia retirement",
    "aptia365 login",
    "aptia365 Mercedes",
    "aptia365 HSA",
    "aptia365 FSA",
    "aptia 365",
    "aptia benefits",
    "aptia",
    "Aptia login",
    "Aptia 365 login",
    "Aptia group",
    "Aptia insurance",
    "Aptia hsa login",
    "Aptia flex benefits",
    "Aptia mercer",
    "Aptia mercedes",
    "Cloud HR software",
    "Aptia365 cobra",
    "Aptia365 com 7 eleven" ,
    "Aptia365 mercer ",
    "Aptia365 TCS",
    "Aptia365 Altice",
    "Aptia365 Altice login",
    "Aptia365 Pearson education inc",
    "Aptia365 Pearson education inc login",
    "Aptia365 Parexel International LLC",
    "Aptia365 Parexel International LLC login",
    "Aptia365 Gainwell Technologies",
    "Aptia365 Gainwell Technologies login",
    "Aptia365 TATA Consultancy Services Limited",
    "Aptia365 TATA Consultancy Services Limited login",
    "Aptia365 Marsh McLennan",
    "Aptia365 Marsh McLennan login",
    "Aptia365 Gainwell Technologies",
    "Aptia365 Gainwell Technologies login",
    "Aptia365 American Residential Services",
    "Aptia365 American Residential Services login",
    "Aptia365 7-eleven",
    "Aptia365 7-eleven login",
    "Aptia365 ABB Inc",
    "Aptia365 ABB Inc login",
    "Aptia365 Envista",
    "Aptia365 Envista login",
    "Aptia365 Cushman & Wakefield",
    "Aptia365 Cushman & Wakefield login",
    "Aptia365 WinnCompanies LLC",
    "Aptia365 WinnCompanies LLC login",
    "Aptia365 Horace Mann",
    "Aptia365 Horace Mann login",
    "Aptia365 PCC Structurals Inc",
    "Aptia365 PCC Structurals Inc login",
    "Aptia365 GEA",
    "Aptia365 GEA login",
    "Aptia365 FormFactor Inc.",
    "Aptia365 FormFactor Inc. login",
    "Aptia365 Evonik",
    "Aptia365 Evonik login",
    "Aptia365 Transamerica",
    "Aptia365 Transamerica login",
    "Aptia365 CareOregon",
    "Aptia365 CareOregon login",
    "Aptia365 Aegis",
    "Aptia365 Aegis login",
    "Aptia365 Motorola Solutions",
    "Aptia365 Motorola Solutions login",
    "Aptia365 Under Armour",
    "Aptia365 Under Armour login",
    "Aptia365 Valvoline LLC",
    "Aptia365 Valvoline LLC login",
    "Aptia365 Chevron Stations Inc",
    "Aptia365 Chevron Stations Inc login",
    "Aptia365 Hill International Inc",
    "Aptia365 Hill International Inc login",
    "Aptia365 PF Holdings",
    "Aptia365 PF Holdings login",
    "Aptia365 Ultradent Products",
    "Aptia365 Ultradent Products login",
    "Aptia365 Peet's Coffee & Tea",
    "Aptia365 Peet's Coffee & Tea login",
    "Aptia365 Ultradent Products Inc",
    "Aptia365 Ultradent Products Inc login",
    "Aptia365 Saudi Aramco Americas",
    "Aptia365 Saudi Aramco Americas login",
    "Aptia365 Johns Hopkins University",
    "Aptia365 Johns Hopkins University login",
    "Aptia365 Mercedes-Benz U.S. International",
    "Aptia365 Mercedes-Benz U.S. International login",
    "Aptia365 Transamerica",
    "Aptia365 Transamerica login",
    "Aptia365 Pearson Education Inc",
    "Aptia365 Pearson Education Inc login",
    "Aptia365 Capital One",
    "Aptia365 Capital One login",
    "Aptia365 Mount St. Mary's University",
    "Aptia365 Mount St. Mary's University login",
    "Aptia365 AvalonBay Communities",
    "Aptia365 AvalonBay Communities login",
    "Aptia365 MERS",
    "Aptia365 MERS login",
    "Aptia365 Lifespan",
    "Aptia365 Lifespan login",
    "Aptia365 ManTech International Corporation",
    "Aptia365 ManTech International Corporation login",
    "Aptia365 Altice",
    "Aptia365 Altice login",
    "Aptia365 Kellogg's",
    "Aptia365 Kellogg's login",
    "Aptia365 Orlando Health",
    "Aptia365 Orlando Health login",
    "Payroll processing solutions",
    "Employee lifecycle management",
    "HRIS (Human Resource Information System)",
    "Benefits administration platform",
    "Time and attendance tracking",
  ],

  openGraph: {
    type: 'website',
    url: "https://www.mercedes-aptia365.com/",
    siteName: "Aptia365"
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col bg-[#F5F5F5]">
          {children}
        </div>
      </body>
    </html>
  );
}
